default_context:
  project_name: 'CurtAPI'
  project_slug: 'curtapi'
  domain_main: 'curtapi.com'
  domain_staging: 'stag.curtapi.com'
  docker_swarm_stack_name_main: 'curtapi-com'
  docker_swarm_stack_name_staging: 'stag-curtapi-com'
  secret_key: 'e92c425584f88cf73e0c823a3c4e5aafe760746e245c5cecd041de033efa4949'
  first_superuser: 'admin@curtapi.com'
  first_superuser_password: '1bf56e7a00d483d85a07b9704508567a4df1eb4cfcd7c51453a8fcd1b19bbe27'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.curtapi.com", "https://stag.curtapi.com", "https://curtapi.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'gmail'
  smtp_user: 'medicurt'
  smtp_password: ''
  smtp_emails_from_email: 'info@curtapi.com'
  postgres_password: 'HeyItsHarambe'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: 'HeyItsHarambe'
  traefik_constraint_tag: 'curtapi.com'
  traefik_constraint_tag_staging: 'stag.curtapi.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: '4a83956606bffb4bcb076cb76f109c912039b7b4ac061a48892986abcd22e20f'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
